apiVersion: v1
kind: ReplicationController
metadata:
  name: webapp
  labels:
    app: ecoblog
    tier: frontend
spec:
  replicas: 2
  # Pod Template
  template:
    metadata:
      labels:
        app: ecoblog
        tier: frontend
    spec:
      containers:
      - name: server
        image: ecoblog

